name: Deploy React Portfolio to Azure

on:
  push:
    branches:
      - master # Triggers workflow when changes are pushed to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies and build the React app
      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      # Step 4: Upload the built files to Azure Blob Storage
      - name: Deploy to Azure Blob Storage
        uses: azure/cli@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --source build \
              --destination '$web' \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }}
        env:
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
